/***************************** BEGIN LICENSE BLOCK ***************************

 The contents of this file are subject to the Mozilla Public License Version
 1.1 (the "License"); you may not use this file except in compliance with
 the License. You may obtain a copy of the License at
 http://www.mozilla.org/MPL/MPL-1.1.html
 
 Software distributed under the License is distributed on an "AS IS" basis,
 WITHOUT WARRANTY OF ANY KIND, either express or implied. See the License
 for the specific language governing rights and limitations under the License.
 
 The Original Code is the "SensorML DataProcessing Engine".
 
 The Initial Developer of the Original Code is the VAST team at the University of Alabama in Huntsville (UAH). <http://vast.uah.edu> Portions created by the Initial Developer are Copyright (C) 2007 the Initial Developer. All Rights Reserved. Please Contact Mike Botts <mike.botts@uah.edu> for more information.
 
 Contributor(s): 
    Alexandre Robin <robin@nsstc.uah.edu>
 
******************************* END LICENSE BLOCK ***************************/

package org.vast.data;

import java.util.List;
import java.util.ListIterator;
import net.opengis.OgcProperty;
import net.opengis.OgcPropertyImpl;
import net.opengis.swe.v20.AbstractDataComponent;
import net.opengis.swe.v20.AbstractEncoding;
import net.opengis.swe.v20.BlockComponent;
import net.opengis.swe.v20.Count;
import net.opengis.swe.v20.DataArray;
import net.opengis.swe.v20.DataStream;
import net.opengis.swe.v20.EncodedValues;
import org.vast.cdm.common.CDMException;
import org.vast.cdm.common.DataBlock;
import org.vast.cdm.common.DataComponent;


/**
 * <p>
 * Growable List of identical DataComponents.
 * Each new cluster of data must comply to the DataList component
 * structure. Data clusters are stored using a DataBlockList so
 * that data can be added and removed in real time.
 * 11-2014: Updated to implement new API autogenerated from XML schema
 * </p>
 *
 * <p>Copyright (c) 2007</p>
 * @author Alexandre Robin
 * @version 1.0
 */
public class DataList extends AbstractDataComponentImpl implements DataArray, DataStream, BlockComponent
{
    private static final long serialVersionUID = 3525149069812989611L;
    protected ListIterator<DataBlock> blockIterator;
    protected AbstractDataComponentImpl tempComponent = null;
    protected OgcPropertyImpl<Count> elementCount = new OgcPropertyImpl<Count>();
    protected OgcPropertyImpl<AbstractDataComponent> elementType = new OgcPropertyImpl<AbstractDataComponent>();
    protected AbstractEncodingImpl encoding;
    protected EncodedValues values = new EncodedValuesImpl();
    

    public DataList()
    {
        this.dataBlock = new DataBlockList();
    }
    
    
    public DataList(String name)
    {
        this();
        this.setName(name);
    }
    
    
    @Override
    public DataList copy()
    {
        DataList newObj = new DataList();
        copyTo(newObj);
        return newObj;
    }
    
    
    protected void copyTo(DataList other)
    {
        super.copyTo(other);
        
        other.elementCount = this.elementCount.copy();        
        other.elementType = this.elementType.copy();
        
        if (this.encoding != null)
            other.encoding = this.encoding.copy();
        else
            other.encoding = null;
    }
    
    
    @Override
    protected void updateStartIndex(int startIndex)
    {        
    }
    
    
    @Override
    protected void updateAtomCount(int childOffsetCount)
    {
    }
    
    
    @Override
    public void addComponent(String name, DataComponent component)
    {
        if (!elementType.hasValue())
        {
            ((AbstractDataComponentImpl)component).parent = this;
            ((AbstractDataComponentImpl)component).name = name;
            elementType.setValue((AbstractDataComponentImpl)component);
            createTempComponent();
        }
    }
    
    
    private void createTempComponent()
    {
        tempComponent = ((AbstractDataComponentImpl)elementType.getValue()).copy();
    }
    
    
    @Override
    public AbstractDataComponentImpl getComponent(int index)
    {
        checkIndex(index);        
        if (tempComponent == null)
            createTempComponent();
        
        tempComponent.setData(((DataBlockList)dataBlock).blockList.get(index));  
        
        return tempComponent;
    }
    
    
    public DataComponent getListComponent()
    {
        return (AbstractDataComponentImpl)elementType.getValue();
    }
    
    
    public void resetIterator()
    {
        blockIterator = ((DataBlockList)dataBlock).blockIterator();
    }
    
    
    public boolean hasNext()
    {
        return blockIterator.hasNext();
    }
    
    
    public AbstractDataComponentImpl nextComponent()
    {
        if (blockIterator == null)
            resetIterator();
        
        if (tempComponent == null)
            createTempComponent();
        
        tempComponent.setData(blockIterator.next());
        
        return tempComponent;
    }
    
    
    public DataBlock nextDataBlock()
    {
        return blockIterator.next();
    }
    
    
    @Override
    public void setData(DataBlock dataBlock)
    {
    	this.dataBlock = (DataBlockList)dataBlock;
    }
    
    
    @Override
    public void clearData()
    {
    	this.dataBlock = new DataBlockList();
    	if (tempComponent != null)
    	    tempComponent.clearData();
    }
    
    
    @Override
    public void validateData(List<CDMException> errorList)
    {
    	// do only if constraints are specified on descendants
    	if (hasConstraints())
    	{
    		int numErrors = errorList.size();
    		
    		for (int i = 0; i < getComponentCount(); i++)
    		{
    			getComponent(i).validateData(errorList);
    			
    			// max N errors generated!
    			if (errorList.size() > numErrors + MAX_ARRAY_ERRORS)
    				return;
    		}
    	}
    }
    
    
    public void addData(DataBlock dataBlock)
    {
    	((DataBlockList)this.dataBlock).add((AbstractDataBlock)dataBlock);
    }
    
    
    @Override
    public AbstractDataBlock createDataBlock()
    {
    	this.dataBlock = new DataBlockList();
    	return this.dataBlock;
    }


    /**
     * Check that the integer index given is in range: 0 to size of array - 1 
     * @param index int
     * @throws DataException
     */
    protected void checkIndex(int index)
    {
        // error if index is out of range
        if ((index >= getComponentCount()) || (index < 0))
            throw new IndexOutOfBoundsException("Index " + index + " is out of bounds");
    }
    
    
    @Override
    public int getComponentCount()
    {
    	return ((DataBlockList)this.dataBlock).getListSize();
    }


    public String toString(String indent)
    {
        StringBuffer text = new StringBuffer();

        text.append("DataList[" + getComponentCount() + "] of:\n");
        text.append(indent + "  ");
        text.append(getComponent(0).toString(indent + "  "));

        return text.toString();
    }
    
    
	@Override
	public boolean hasConstraints()
	{
	    return ((DataValue)elementType.getValue()).hasConstraints();
	}


    @Override
    public int getComponentIndex(String name)
    {
        if (!elementType.getName().equals(name))
            return -1;
        return 0;
    }


    @Override
    public DataComponent getComponent(String name)
    {
        if (!name.equals(elementType.getName()))
            return null;
        
        return getListComponent();
    }


    /* ************************************ */
    /*  Auto-generated Getters and Setters  */    
    /* ************************************ */
    
    /**
     * Gets the elementCount property
     */
    @Override
    public Count getElementCount()
    {
        return elementCount.getValue();
    }
    
    
    /**
     * Gets extra info (name, xlink, etc.) carried by the elementCount property
     */
    @Override
    public OgcProperty<Count> getElementCountProperty()
    {
        return elementCount;
    }
    
    
    @Override
    public boolean isSetElementCount()
    {
        return (elementCount != null && (elementCount.hasValue() || elementCount.hasHref()));
    }
    
    
    /**
     * Sets the elementCount property
     */
    @Override
    public void setElementCount(Count elementCount)
    {
        this.elementCount.setValue(elementCount);
    }
    
    
    /**
     * Gets the elementType property
     */
    @Override
    public DataComponent getElementType()
    {
        return (DataComponent)elementType.getValue();
    }
    
    
    @Override
    public OgcProperty<AbstractDataComponent> getElementTypeProperty()
    {
        return elementType;
    }
    
    
    /**
     * Sets the elementType property
     */
    @Override
    public void setElementType(String name, AbstractDataComponent elementType)
    {
        addComponent(name, (AbstractDataComponentImpl)elementType);
    }
    
    
    /**
     * Gets the encoding property
     */
    @Override
    public AbstractEncoding getEncoding()
    {
        return encoding;
    }
    
    
    /**
     * Checks if encoding is set
     */
    @Override
    public boolean isSetEncoding()
    {
        return (encoding != null);
    }
    
    
    /**
     * Sets the encoding property
     */
    @Override
    public void setEncoding(AbstractEncoding encoding)
    {
        this.encoding = (AbstractEncodingImpl)encoding;
    }
    
    
    /**
     * Gets the values property
     */
    @Override
    public EncodedValues getValues()
    {
        return values;
    }
    
    
    /**
     * Checks if values is set
     */
    @Override
    public boolean isSetValues()
    {
        return (getComponentCount() > 0);
    }
    
    
    /**
     * Sets the values property
     */
    @Override
    public void setValues(EncodedValues values)
    {
        this.values = values;
    }
}
