/***************************** BEGIN LICENSE BLOCK ***************************

 The contents of this file are subject to the Mozilla Public License Version
 1.1 (the "License"); you may not use this file except in compliance with
 the License. You may obtain a copy of the License at
 http://www.mozilla.org/MPL/MPL-1.1.html
 
 Software distributed under the License is distributed on an "AS IS" basis,
 WITHOUT WARRANTY OF ANY KIND, either express or implied. See the License
 for the specific language governing rights and limitations under the License.
 
 The Initial Developer of the Original Code is SENSIA SOFTWARE LLC.
 Portions created by the Initial Developer are Copyright (C) 2012
 the Initial Developer. All Rights Reserved.

 Please Contact Alexandre Robin <alex.robin@sensiasoftware.com> for more
 information.
 
 Contributor(s): 
    Alexandre Robin <alex.robin@sensiasoftware.com>
 
******************************* END LICENSE BLOCK ***************************/

package org.vast.util;

import java.io.IOException;


/**
 * <p>
 * Exception generated by reader implementations
 * </p>
 *
 * @author Alex Robin
 * @since Nov 18, 2012
 * */
public class ReaderException extends IOException
{
    private static final long serialVersionUID = 3623156292080498179L;
    

    public ReaderException(Exception e)
    {
        super(e);
    }
    
    
    public ReaderException(String message)
    {
        super(message);
    }
       
    
    public ReaderException(String message, Exception e)
    {
        super(message, e);
    }
}
